# Generated by Django 5.2.1 on 2025-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
