# Generated by Django 5.2.1 on 2025-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_tool_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
