# Generated by Django 5.2.1 on 2025-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AI Writing', 'AI Writing'), ('Code Tools', 'Code Tools'), ('Image Generation', 'Image Generation'), ('Productivity', 'Productivity'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
