# Generated by Django 5.2.1 on 2025-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_tool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
