# Generated by Django 5.2.1 on 2025-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_tool_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Business & Productivity', 'Business & Productivity'), ('Education & Knowledge', 'Education & Knowledge'), ('Environmental', 'Environmental'), ('Food & Nutrition', 'Food & Nutrition'), ('Government & Public Sector', 'Government & Public Sector'), ('Health & Wellness', 'Health & Wellness'), ('Language & Communication', 'Language & Communication'), ('Media & Entertainment', 'Media & Entertainment'), ('NFT & Blockchain', 'NFT & Blockchain'), ('Personal & Lifestyle', 'Personal & Lifestyle'), ('Security & Privacy', 'Security & Privacy'), ('Sports', 'Sports'), ('Tech & Engineering', 'Tech & Engineering'), ('Travel & Navigation', 'Travel & Navigation'), ('Utilities & Tools', 'Utilities & Tools'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
