# Generated by Django 5.2.1 on 2025-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
